/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tenant/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 店舗一覧取得
         * @description テナントに紐づく店舗の一覧を取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 店舗ID */
                            id: number;
                            /** @description 店舗名 */
                            name: string;
                            /** @description 住所 */
                            address?: string | null;
                            /** @description 電話番号 */
                            phone?: string | null;
                            /** @description 有効/無効 */
                            active: boolean;
                            /**
                             * Format: date-time
                             * @description 作成日時
                             */
                            created_at: string;
                            /**
                             * Format: date-time
                             * @description 更新日時
                             */
                            updated_at: string;
                        }[];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 店舗作成
         * @description 新しい店舗を作成します。manager以上の権限が必要です。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        store: {
                            /** @description 店舗名 */
                            name: string;
                            /** @description 住所 */
                            address?: string;
                            /** @description 電話番号 */
                            phone?: string;
                            /**
                             * @description 有効/無効
                             * @default true
                             */
                            active?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description 店舗作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 店舗ID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * 店舗詳細取得
         * @description 指定した店舗の詳細情報を取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 店舗削除
         * @description 指定した店舗を削除します。manager以上の権限が必要です。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 店舗更新
         * @description 指定した店舗の情報を更新します。manager以上の権限が必要です。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        store: {
                            /** @description 店舗名 */
                            name?: string;
                            /** @description 住所 */
                            address?: string;
                            /** @description 電話番号 */
                            phone?: string;
                            /** @description 有効/無効 */
                            active?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description 店舗更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description エラーメッセージの配列 */
            errors: string[];
        };
        PaginationMeta: {
            current_page?: number;
            total_pages?: number;
            total_count?: number;
            per_page?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
