/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/store/kitchen_queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 厨房キュー一覧取得
         * @description 厨房の調理キュー一覧を取得します。アクティブなキューのみを優先度順に返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description キュー一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            order_id: number;
                            /** @enum {string} */
                            status: "waiting" | "in_progress" | "completed";
                            priority: number;
                            notes?: string | null;
                            order: {
                                id?: number;
                                order_number?: string;
                                order_items?: {
                                    id?: number;
                                    menu_item_name?: string;
                                    quantity?: number;
                                    notes?: string | null;
                                }[];
                            };
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/kitchen_queues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description キューID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * キュー詳細取得
         * @description 指定したキューの詳細情報を取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キューID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description キュー詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description キューが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * キュー更新
         * @description キューの情報（優先度、メモ）を更新します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キューID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        kitchen_queue: {
                            priority?: number;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description キュー更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description キューが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/kitchen_queues/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description キューID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 調理開始
         * @description キューの調理を開始します。ステータスをwaiting→in_progressに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キューID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 調理開始成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 調理開始できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/kitchen_queues/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description キューID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 調理完了
         * @description キューの調理を完了します。ステータスをin_progress→completedに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キューID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 調理完了成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 完了できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 注文一覧取得
         * @description 店舗の注文一覧を取得します。statusパラメータでフィルタリング可能です。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 注文ステータスフィルター (pending, cooking, ready, delivered, paid) */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 注文一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            order_number: string;
                            /** @enum {string} */
                            status: "pending" | "cooking" | "ready" | "delivered" | "paid";
                            table_id?: number | null;
                            total_amount: number;
                            notes?: string | null;
                            order_items: {
                                id?: number;
                                menu_item_id?: number;
                                menu_item_name?: string;
                                quantity?: number;
                                unit_price?: number;
                                subtotal?: number;
                                notes?: string | null;
                            }[];
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /**
         * 注文作成
         * @description 新しい注文を作成します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        order: {
                            table_id?: number;
                            notes?: string;
                            order_items_attributes: {
                                menu_item_id: number;
                                quantity: number;
                                notes?: string;
                            }[];
                        };
                    };
                };
            };
            responses: {
                /** @description 注文作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注文ID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * 注文詳細取得
         * @description 指定した注文の詳細情報を取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 注文ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 注文詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 注文が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 注文更新
         * @description 指定した注文の情報を更新します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 注文ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        order: {
                            table_id?: number;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description 注文更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 注文が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/orders/{id}/start_cooking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注文ID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 調理開始
         * @description 注文の調理を開始します。ステータスをpending→cookingに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 注文ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 調理開始成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 調理開始できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/orders/{id}/mark_as_ready": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注文ID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 調理完了
         * @description 注文の調理を完了します。ステータスをcooking→readyに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 注文ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 調理完了成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 調理完了にできない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/orders/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注文ID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 配膳完了
         * @description 注文の配膳を完了します。ステータスをready→deliveredに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 注文ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 配膳完了成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 配膳できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/store/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 支払い一覧取得
         * @description 店舗の支払い一覧を取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支払い一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            order_id: number;
                            /** @enum {string} */
                            payment_method: "cash" | "credit_card" | "qr_code" | "other";
                            amount: number;
                            /** @enum {string} */
                            status: "pending" | "completed" | "failed";
                            notes?: string | null;
                            order: {
                                id?: number;
                                order_number?: string;
                                total_amount?: number;
                            };
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /**
         * 支払い作成
         * @description 注文に対する支払いを作成します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        payment: {
                            /** @description 注文ID */
                            order_id: number;
                            /**
                             * @description 支払い方法
                             * @enum {string}
                             */
                            payment_method: "cash" | "credit_card" | "qr_code" | "other";
                            /** @description メモ */
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description 支払い作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 会計できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支払いID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * 支払い詳細取得
         * @description 指定した支払いの詳細情報を取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 支払いID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支払い詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 支払いが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/payments/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支払いID */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 支払い完了
         * @description 支払いを完了します。ステータスをpending→completedに変更し、注文ステータスをpaidに変更します。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 支払いID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支払い完了成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 完了できない状態 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/tenant/menu_items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * メニュー一覧取得
         * @description テナントのメニュー一覧を取得します。
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページ番号 */
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メニュー一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            price: number;
                            category?: string | null;
                            available: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /**
         * メニュー作成
         * @description 新しいメニューを作成します。manager以上の権限が必要です。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        menu_item: {
                            name: string;
                            price: number;
                            category?: string;
                            /** @default true */
                            available?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description メニュー作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/menu_items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** メニュー詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メニュー詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description メニューが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** メニュー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メニュー削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** メニュー更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        menu_item?: {
                            name?: string;
                            price?: number;
                            category?: string;
                            available?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description メニュー更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/tenant/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 日次売上レポート
         * @description 指定日の売上レポートを取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 日付 (YYYY-MM-DD形式、省略時は今日) */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 日次レポート取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            date?: string;
                            total_orders?: number;
                            total_amount?: number;
                            active_orders?: number;
                            orders?: {
                                id?: number;
                                order_number?: string;
                                total_amount?: number;
                                /** Format: date-time */
                                created_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 月次売上レポート
         * @description 指定月の売上レポートを取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 年 (省略時は今年) */
                    year?: number;
                    /** @description 月 (省略時は今月) */
                    month?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 月次レポート取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            year?: number;
                            month?: number;
                            total_orders?: number;
                            total_amount?: number;
                            daily_breakdown?: {
                                [key: string]: {
                                    total_orders?: number;
                                    total_amount?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/reports/by_menu_item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * メニュー別売上レポート
         * @description メニュー項目別の売上を取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 開始日 (YYYY-MM-DD形式、省略時は1ヶ月前) */
                    start_date?: string;
                    /** @description 終了日 (YYYY-MM-DD形式、省略時は今日) */
                    end_date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メニュー別レポート取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            menu_item_id?: number;
                            menu_item_name?: string;
                            total_quantity?: number;
                            total_sales?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 店舗一覧取得
         * @description テナントに紐づく店舗の一覧を取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 店舗ID */
                            id: number;
                            /** @description 店舗名 */
                            name: string;
                            /** @description 住所 */
                            address?: string | null;
                            /** @description 電話番号 */
                            phone?: string | null;
                            /** @description 有効/無効 */
                            active: boolean;
                            /**
                             * Format: date-time
                             * @description 作成日時
                             */
                            created_at: string;
                            /**
                             * Format: date-time
                             * @description 更新日時
                             */
                            updated_at: string;
                        }[];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 店舗作成
         * @description 新しい店舗を作成します。manager以上の権限が必要です。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        store: {
                            /** @description 店舗名 */
                            name: string;
                            /** @description 住所 */
                            address?: string;
                            /** @description 電話番号 */
                            phone?: string;
                            /**
                             * @description 有効/無効
                             * @default true
                             */
                            active?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description 店舗作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 店舗ID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * 店舗詳細取得
         * @description 指定した店舗の詳細情報を取得します。manager以上の権限が必要です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 店舗削除
         * @description 指定した店舗を削除します。manager以上の権限が必要です。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 店舗削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 店舗更新
         * @description 指定した店舗の情報を更新します。manager以上の権限が必要です。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 店舗ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        store: {
                            /** @description 店舗名 */
                            name?: string;
                            /** @description 住所 */
                            address?: string;
                            /** @description 電話番号 */
                            phone?: string;
                            /** @description 有効/無効 */
                            active?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description 店舗更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            address?: string | null;
                            phone?: string | null;
                            active: boolean;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 店舗が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tenant/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー一覧取得
         * @description テナントに紐づくユーザーの一覧を取得します。全てのロールで閲覧可能です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ユーザーID */
                            id: number;
                            /** @description ユーザー名 */
                            name: string;
                            /** @description メールアドレス */
                            email: string;
                            /**
                             * @description ロール
                             * @enum {string}
                             */
                            role: "owner" | "manager" | "staff" | "kitchen_staff" | "cashier";
                            /**
                             * Format: date-time
                             * @description 作成日時
                             */
                            created_at: string;
                            /**
                             * Format: date-time
                             * @description 更新日時
                             */
                            updated_at: string;
                        }[];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * ユーザー作成
         * @description 新しいユーザーを作成します。owner権限が必要です。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        user: {
                            /** @description ユーザー名 */
                            name: string;
                            /** @description メールアドレス */
                            email: string;
                            /** @description パスワード (8文字以上) */
                            password?: string;
                            /**
                             * @description ロール
                             * @enum {string}
                             */
                            role: "owner" | "manager" | "staff" | "kitchen_staff" | "cashier";
                        };
                    };
                };
            };
            responses: {
                /** @description ユーザー作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            email: string;
                            role: string;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                id: number;
            };
            cookie?: never;
        };
        /**
         * ユーザー詳細取得
         * @description 指定したユーザーの詳細情報を取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー詳細取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            email: string;
                            role: string;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ユーザーが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * ユーザー削除
         * @description 指定したユーザーを削除します。owner権限が必要です。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ユーザーが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * ユーザー更新
         * @description 指定したユーザーの情報を更新します。owner権限が必要です。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        user: {
                            /** @description ユーザー名 */
                            name?: string;
                            /** @description メールアドレス */
                            email?: string;
                            /** @description パスワード (8文字以上、変更する場合のみ) */
                            password?: string;
                            /**
                             * @description ロール
                             * @enum {string}
                             */
                            role?: "owner" | "manager" | "staff" | "kitchen_staff" | "cashier";
                        };
                    };
                };
            };
            responses: {
                /** @description ユーザー更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            email: string;
                            role: string;
                            /** Format: date-time */
                            created_at: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ユーザーが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description エラーメッセージの配列 */
            errors: string[];
        };
        PaginationMeta: {
            current_page?: number;
            total_pages?: number;
            total_count?: number;
            per_page?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
